#!/usr/bin/env bash
# Copyright 2026 Théau d'Audiffret, Mariia Vladimirova, Jean-Yves Franceschi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stable Diffusion 1.5 adapter (Appendix C): training cache, then training.
set -euo pipefail
cd "$(dirname "$0")/../.."
# 1. 50,000 images generated by SD 1.5 from the 20 neutral prompts of conf/sd15/adapter_prompts.yaml
#    (conf/sd15/adapter_cache.yaml), with their latents and SigLIP 2 targets.
uv run python scripts/sd15/build_adapter_cache.py
# 2. Adapter (conf/sd15/adapter.yaml). The checkpoint kept is the epoch of best validation
#    R@1, written to checkpoints/sd15_adapter.pth.
uv run python scripts/sd15/train_adapter.py
